wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_meanIOU
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_meanIOU
      5: 1
      6:
      - 1
    - 1: mean_weight_norm
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    - 1: test_meanIOU
      5: 1
      6:
      - 1
    python_version: 3.9.12
    start_time: 1684333130.15414
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.9.12
      5: 0.14.0
      8:
      - 5
arg_log:
  desc: null
  value: false
batch_size:
  desc: null
  value: 32
config:
  desc: null
  value: configs/kenya/kenya_wo_kisumu.cfg
init_from_pretrained:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0001
model_checkpoint:
  desc: null
  value: null
monitor_metric:
  desc: null
  value: val_loss
num_bands:
  desc: null
  value: 4
pos_weight:
  desc: null
  value: 1.0
pretrained_checkpoint:
  desc: null
  value: /data/shared/deeplabsegm/src/deeplnafrica/../../trained_models/self_supervised/vmiw49yz/checkpoints/last-step=30900.ckpt
random_seed:
  desc: null
  value: 42
test_cities:
  desc: null
  value:
  - kenya_kisumu
test_split:
  desc: null
  value: 0.0
tile_size:
  desc: null
  value: 128
train_cities:
  desc: null
  value:
  - kenya_nairobi_eastleigh
  - kenya_nairobi_kawangware
  - kenya_nairobi_kibera
  - kenya_nairobi_korochogo
  - kenya_nairobi_lavington
  - kenya_nairobi_mathare
  - kenya_nairobi_muthaiga
  - kenya_nairobi_runda
  - kenya_nairobi_viwandani
train_model:
  desc: null
  value: true
use_data_augmentation:
  desc: null
  value: false
val_every_n_epochs:
  desc: null
  value: 1
val_split_from_train:
  desc: null
  value: 0.1
weight_decay:
  desc: null
  value: 0.01
