name: rv
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.5=py311h05b510d_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.22=hec39e38_2
  - aws-c-cal=0.6.14=h5db4892_1
  - aws-c-common=0.9.19=h99b78c6_0
  - aws-c-compression=0.2.18=h5db4892_6
  - aws-c-event-stream=0.4.2=h5eab607_12
  - aws-c-http=0.8.1=had10953_17
  - aws-c-io=0.14.8=hb5a7b21_5
  - aws-c-mqtt=0.10.4=h78534b8_4
  - aws-c-s3=0.5.9=h1755d02_3
  - aws-c-sdkutils=0.1.16=h5db4892_2
  - aws-checksums=0.1.18=h5db4892_6
  - aws-crt-cpp=0.26.9=h03bff2b_0
  - aws-sdk-cpp=1.11.329=hb37a6d0_3
  - bokeh=3.4.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.28.1=h93a5062_0
  - ca-certificates=2024.6.2=hf0a4a13_0
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py311h4a08483_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py311hcc98501_0
  - cryptography=42.0.7=py311hcaeb4ce_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py311h05b510d_0
  - dask=2024.5.1=pyhd8ed1ab_0
  - dask-core=2024.5.1=pyhd8ed1ab_0
  - dask-expr=1.1.1=pyhd8ed1ab_1
  - dask-gateway=2024.1.0=pyh8af1aa0_0
  - debugpy=1.8.1=py311h92babd0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2024.5.1=pyhd8ed1ab_0
  - earthengine-api=0.1.336=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.14.0=pyhd8ed1ab_0
  - fonttools=4.52.1=py311hd3f4193_0
  - freetype=2.12.1=hadb7bae_2
  - frozenlist=1.4.1=py311h05b510d_0
  - fsspec=2024.5.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - gflags=2.2.2=hc88da5d_1004
  - glog=0.7.0=hc6770e3_0
  - gmp=6.3.0=hebf3989_1
  - gmpy2=2.1.5=py311h1e33d93_1
  - google-api-core=2.19.0=pyhd8ed1ab_0
  - google-api-python-client=2.130.0=pyhd8ed1ab_0
  - google-auth=2.29.0=pyhca7485f_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_0
  - google-cloud-core=2.4.1=pyhd8ed1ab_0
  - google-cloud-storage=2.16.0=pyhca7485f_0
  - google-crc32c=1.1.2=py311h533d1a3_5
  - google-resumable-media=2.7.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.63.0=pyhd8ed1ab_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.24.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_hebf3989_0
  - libarrow=16.1.0=h28dd788_6_cpu
  - libarrow-acero=16.1.0=h00cdb27_6_cpu
  - libarrow-dataset=16.1.0=h00cdb27_6_cpu
  - libarrow-substrait=16.1.0=hc68f6b8_6_cpu
  - libblas=3.9.0=22_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.8.0=h7b6f9a7_0
  - libcxx=17.0.6=h5f092b4_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libgoogle-cloud=2.24.0=hfe08963_0
  - libgoogle-cloud-storage=2.24.0=h3fa5b87_0
  - libgrpc=1.62.2=h9c18a4f_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=22_osxarm64_openblas
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libparquet=16.1.0=hcf52c46_6_cpu
  - libpng=1.6.43=h091b4b1_0
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.3=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=h07db509_3
  - libtorch=2.3.0=cpu_generic_hac4f340_1
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libuv=1.48.0=h93a5062_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.15=hf346824_0
  - libzlib=1.2.13=h53f4e23_5
  - lightning=2.2.5=pyhd8ed1ab_0
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=18.1.5=hde57baf_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311hd44b8e9_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=2.1.5=py311h05b510d_0
  - matplotlib-base=3.8.4=py311h000fb6e_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h41d338b_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py311h6bde47b_0
  - multidict=6.0.5=py311he2be06e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=hb89a1cb_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.1=hfb2fe0b_0
  - orc=2.0.1=h47ade37_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py311h4b4568b_1
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py311h0b5d0a1_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - proto-plus=1.23.0=pyhd8ed1ab_0
  - psutil=5.9.8=py311h05b510d_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=16.1.0=py311hf3b2ce4_1
  - pyarrow-core=16.1.0=py311hbc16ef1_1_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytorch=2.3.0=cpu_generic_py311h82099cb_1
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=26.0.3=py311h9bed540_0
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - requests=2.32.2=pyhd8ed1ab_0
  - scipy=1.13.1=py311hceeca8c_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=70.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h156473d_2
  - snappy=1.2.0=hd04f947_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py311h5d790af_0
  - sympy=1.12=pypyh9d50eac_103
  - tblib=3.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - toolz=0.12.1=pyhd8ed1ab_0
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - tornado=6.4=py311h05b510d_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xyzservices=2024.4.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py311h05b510d_0
  - zeromq=4.3.5=hcc0f68c_4
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - absl-py==2.1.0
      - affine==2.4.0
      - albumentations==1.4.3
      - awscli==1.32.113
      - boto3==1.34.113
      - botocore==1.34.113
      - click-plugins==1.1.1
      - cligj==0.7.2
      - configobj==5.0.8
      - cython==3.0.10
      - docker-pycreds==0.4.0
      - docutils==0.16
      - everett==3.3.0
      - fiona==1.9.6
      - geopandas==0.14.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.64.0
      - humanize==4.9.0
      - imageio==2.34.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - lazy-loader==0.4
      - markdown==3.6
      - matplotlib==3.9.0
      - onnx==1.16.1
      - opencv-python-headless==4.9.0.80
      - planetary-computer==1.0.0
      - protobuf==5.27.0
      - py6s==1.9.2
      - pycocotools==2.0.7
      - pydantic==1.10.15
      - pyproj==3.6.1
      - pysolar==0.11
      - pystac==1.10.1
      - pystac-client==0.8.1
      - python-dotenv==1.0.1
      - pytorch-lightning==2.0.0
      - rasterio==1.3.10
      - rastervision-aws-s3==0.30.1
      - rastervision-core==0.30.0
      - rastervision-pipeline==0.30.0
      - rastervision-pytorch-backend==0.30.0
      - rastervision-pytorch-learner==0.30.0
      - referencing==0.35.1
      - rpds-py==0.18.1
      - rsa==4.7.2
      - s3transfer==0.10.1
      - scikit-image==0.23.2
      - scikit-learn==1.5.0
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - shapely==2.0.4
      - smmap==5.0.1
      - snuggs==1.4.7
      - stackstac==0.5.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tifffile==2024.5.22
      - torchvision==0.18.0
      - wandb==0.17.1
      - werkzeug==3.0.3
      - xarray==2024.5.0
prefix: /opt/miniconda3/envs/rv
