wandb_version: 1

model:
  desc: null
  value: DLV3
train_cities:
  desc: null
  value: SDGC
batch_size:
  desc: null
  value: 16
use_deeplnafrica:
  desc: null
  value: true
labels_size:
  desc: null
  value: 256
buil_channels:
  desc: null
  value: 64
atrous_rates:
  desc: null
  value:
  - 12
  - 24
  - 36
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0001
gamma:
  desc: null
  value: 0.8
sched_step_size:
  desc: null
  value: 10
pos_weight:
  desc: null
  value: 2.0
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.1
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719869032
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 54
      - 55
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 54
      - 55
      - 80
      - 103
      3:
      - 2
      - 16
      - 23
      4: 3.11.9
      5: 0.17.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
