wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.1
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718538692
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 54
      - 55
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 54
      - 55
      - 80
      - 103
      3:
      - 23
      4: 3.11.9
      5: 0.17.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
